set_property SRC_FILE_INFO {cfile:D:/projets/map2_dijkstra/project_1/project_1.srcs/constrs_1/imports/Desktop/zybo-z7-20.xdc rfile:../../../project_1.srcs/constrs_1/imports/Desktop/zybo-z7-20.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V15 IOSTANDARD LVCMOS33} [get_ports HOLO_UART_txd]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W15 IOSTANDARD LVCMOS33} [get_ports HOLO_UART_rxd]
