set_property SRC_FILE_INFO {cfile:D:/projets/2020_2/project_FPGA/project_FPGA.srcs/constrs_1/imports/Desktop/zybo-z7-20.xdc rfile:../../../project_FPGA.srcs/constrs_1/imports/Desktop/zybo-z7-20.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33     } [get_ports { HOLO_UART_txd }]; #IO_L10P_T1_34 Sch=jc_p[1]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W15   IOSTANDARD LVCMOS33     } [get_ports { HOLO_UART_rxd }]; #IO_L10N_T1_34 Sch=jc_n[1]
