# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projets/map2_dijkstra/project_1/project_1.srcs/sources_1/bd/design_dijkstra_reg/ip/design_dijkstra_reg_xbar_0/design_dijkstra_reg_xbar_0.xci
# IP: The module: 'design_dijkstra_reg_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/map2_dijkstra/project_1/project_1.gen/sources_1/bd/design_dijkstra_reg/ip/design_dijkstra_reg_xbar_0/design_dijkstra_reg_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dijkstra_reg_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/projets/map2_dijkstra/project_1/project_1.srcs/sources_1/bd/design_dijkstra_reg/ip/design_dijkstra_reg_xbar_0/design_dijkstra_reg_xbar_0.xci
# IP: The module: 'design_dijkstra_reg_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/map2_dijkstra/project_1/project_1.gen/sources_1/bd/design_dijkstra_reg/ip/design_dijkstra_reg_xbar_0/design_dijkstra_reg_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dijkstra_reg_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
