# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_dijkstra_reg/design_dijkstra_reg.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg || ORIG_REF_NAME==design_dijkstra_reg} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_axi_uartlite_0_0/design_dijkstra_reg_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_axi_uartlite_0_0 || ORIG_REF_NAME==design_dijkstra_reg_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_processing_system7_0_0/design_dijkstra_reg_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_processing_system7_0_0 || ORIG_REF_NAME==design_dijkstra_reg_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_xbar_0/design_dijkstra_reg_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_xbar_0 || ORIG_REF_NAME==design_dijkstra_reg_xbar_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_ps7_0_axi_periph_0/design_dijkstra_reg_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_dijkstra_reg_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_rst_ps7_0_50M_0/design_dijkstra_reg_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_dijkstra_reg_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_Dijkstra_reg_0_0/design_dijkstra_reg_Dijkstra_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_Dijkstra_reg_0_0 || ORIG_REF_NAME==design_dijkstra_reg_Dijkstra_reg_0_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_auto_pc_2/design_dijkstra_reg_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_auto_pc_2 || ORIG_REF_NAME==design_dijkstra_reg_auto_pc_2} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_auto_pc_0/design_dijkstra_reg_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_auto_pc_0 || ORIG_REF_NAME==design_dijkstra_reg_auto_pc_0} -quiet] -quiet

# IP: bd/design_dijkstra_reg/ip/design_dijkstra_reg_auto_pc_1/design_dijkstra_reg_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dijkstra_reg_auto_pc_1 || ORIG_REF_NAME==design_dijkstra_reg_auto_pc_1} -quiet] -quiet

# XDC: d:/projets/map2_dijkstra/project_1/project_1.gen/sources_1/bd/design_dijkstra_reg/design_dijkstra_reg_ooc.xdc
