# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_UART/design_UART.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_UART || ORIG_REF_NAME==design_UART} -quiet] -quiet

# IP: bd/design_UART/ip/design_UART_UART_controller_0_0/design_UART_UART_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_UART_UART_controller_0_0 || ORIG_REF_NAME==design_UART_UART_controller_0_0} -quiet] -quiet

# IP: bd/design_UART/ip/design_UART_xlconstant_0_1/design_UART_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_UART_xlconstant_0_1 || ORIG_REF_NAME==design_UART_xlconstant_0_1} -quiet] -quiet

# XDC: bd/design_UART/design_UART_ooc.xdc
