# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_IMU/design_IMU.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU || ORIG_REF_NAME==design_IMU} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_blk_mem_gen_0_0/design_IMU_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_blk_mem_gen_0_0 || ORIG_REF_NAME==design_IMU_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_time_pulse_0_0/design_IMU_time_pulse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_time_pulse_0_0 || ORIG_REF_NAME==design_IMU_time_pulse_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_ila_0_0/design_IMU_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_ila_0_0 || ORIG_REF_NAME==design_IMU_ila_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_IO_buffer_0_0/design_IMU_IO_buffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_IO_buffer_0_0 || ORIG_REF_NAME==design_IMU_IO_buffer_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_IO_buffer_1_0/design_IMU_IO_buffer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_IO_buffer_1_0 || ORIG_REF_NAME==design_IMU_IO_buffer_1_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_xlconstant_0_0/design_IMU_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_xlconstant_0_0 || ORIG_REF_NAME==design_IMU_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_filtre_anti_rebond_0_0/design_IMU_filtre_anti_rebond_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_filtre_anti_rebond_0_0 || ORIG_REF_NAME==design_IMU_filtre_anti_rebond_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_I2C_master_0_0/design_IMU_I2C_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_I2C_master_0_0 || ORIG_REF_NAME==design_IMU_I2C_master_0_0} -quiet] -quiet

# IP: bd/design_IMU/ip/design_IMU_IMU_control_0_0/design_IMU_IMU_control_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_IMU_control_0_0 || ORIG_REF_NAME==design_IMU_IMU_control_0_0} -quiet] -quiet

# XDC: d:/project_IMU/project_IMU.gen/sources_1/bd/design_IMU/design_IMU_ooc.xdc
