# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_IMU_AXI/design_IMU_AXI.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI || ORIG_REF_NAME==design_IMU_AXI} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_processing_system7_0_0/design_IMU_AXI_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_processing_system7_0_0 || ORIG_REF_NAME==design_IMU_AXI_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_ps7_0_axi_periph_0/design_IMU_AXI_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_IMU_AXI_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_IMU_AXI_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_IO_buffer_0_0/design_IMU_AXI_IO_buffer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_IO_buffer_0_0 || ORIG_REF_NAME==design_IMU_AXI_IO_buffer_0_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_time_pulse_0_0/design_IMU_AXI_time_pulse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_time_pulse_0_0 || ORIG_REF_NAME==design_IMU_AXI_time_pulse_0_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_I2C_master_0_0/design_IMU_AXI_I2C_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_I2C_master_0_0 || ORIG_REF_NAME==design_IMU_AXI_I2C_master_0_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_IO_buffer_0_1/design_IMU_AXI_IO_buffer_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_IO_buffer_0_1 || ORIG_REF_NAME==design_IMU_AXI_IO_buffer_0_1} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_IP_IMU_0_0/design_IMU_AXI_IP_IMU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_IP_IMU_0_0 || ORIG_REF_NAME==design_IMU_AXI_IP_IMU_0_0} -quiet] -quiet

# IP: bd/design_IMU_AXI/ip/design_IMU_AXI_auto_pc_0/design_IMU_AXI_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IMU_AXI_auto_pc_0 || ORIG_REF_NAME==design_IMU_AXI_auto_pc_0} -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/design_IMU_AXI_ooc.xdc
