# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_test_ultrason/design_test_ultrason.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_ultrason || ORIG_REF_NAME==design_test_ultrason} -quiet] -quiet

# IP: bd/design_test_ultrason/ip/design_test_ultrason_time_pulse_0_0/design_test_ultrason_time_pulse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_ultrason_time_pulse_0_0 || ORIG_REF_NAME==design_test_ultrason_time_pulse_0_0} -quiet] -quiet

# IP: bd/design_test_ultrason/ip/design_test_ultrason_clk_wiz_0/design_test_ultrason_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_ultrason_clk_wiz_0 || ORIG_REF_NAME==design_test_ultrason_clk_wiz_0} -quiet] -quiet

# IP: bd/design_test_ultrason/ip/design_test_ultrason_Ultrason_0_0/design_test_ultrason_Ultrason_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_ultrason_Ultrason_0_0 || ORIG_REF_NAME==design_test_ultrason_Ultrason_0_0} -quiet] -quiet

# IP: bd/design_test_ultrason/ip/design_test_ultrason_ila_0_0/design_test_ultrason_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_ultrason_ila_0_0 || ORIG_REF_NAME==design_test_ultrason_ila_0_0} -quiet] -quiet

# IP: bd/design_test_ultrason/ip/design_test_ultrason_test_interface_0_0/design_test_ultrason_test_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_ultrason_test_interface_0_0 || ORIG_REF_NAME==design_test_ultrason_test_interface_0_0} -quiet] -quiet

# XDC: d:/projets/2020_2/project_ultrason/project_ultrason.gen/sources_1/bd/design_test_ultrason/design_test_ultrason_ooc.xdc
