# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_IP_I2C/design_IP_I2C.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_I2C || ORIG_REF_NAME==design_IP_I2C} -quiet] -quiet

# IP: bd/design_IP_I2C/ip/design_IP_I2C_processing_system7_0_0/design_IP_I2C_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_I2C_processing_system7_0_0 || ORIG_REF_NAME==design_IP_I2C_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_I2C_axi_iic_0_0 || ORIG_REF_NAME==design_IP_I2C_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_IP_I2C/ip/design_IP_I2C_auto_pc_0/design_IP_I2C_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_I2C_auto_pc_0 || ORIG_REF_NAME==design_IP_I2C_auto_pc_0} -quiet] -quiet

# IP: bd/design_IP_I2C/ip/design_IP_I2C_ps7_0_axi_periph_0/design_IP_I2C_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_I2C_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_IP_I2C_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_IP_I2C/ip/design_IP_I2C_rst_ps7_0_50M_0/design_IP_I2C_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_I2C_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_IP_I2C_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IP_I2C/design_IP_I2C_ooc.xdc
