# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projets/2020_2/project_FPGA/project_FPGA.srcs/sources_1/bd/design_dijkstra_ram/ip/design_dijkstra_ram_xbar_0/design_dijkstra_ram_xbar_0.xci
# IP: The module: 'design_dijkstra_ram_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_FPGA/project_FPGA.gen/sources_1/bd/design_dijkstra_ram/ip/design_dijkstra_ram_xbar_0/design_dijkstra_ram_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dijkstra_ram_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/projets/2020_2/project_FPGA/project_FPGA.srcs/sources_1/bd/design_dijkstra_ram/ip/design_dijkstra_ram_xbar_0/design_dijkstra_ram_xbar_0.xci
# IP: The module: 'design_dijkstra_ram_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_FPGA/project_FPGA.gen/sources_1/bd/design_dijkstra_ram/ip/design_dijkstra_ram_xbar_0/design_dijkstra_ram_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dijkstra_ram_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
