# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_IP_RFID/design_IP_RFID.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID || ORIG_REF_NAME==design_IP_RFID} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_RFID_reader_0_0/design_IP_RFID_RFID_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_RFID_reader_0_0 || ORIG_REF_NAME==design_IP_RFID_RFID_reader_0_0} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_processing_system7_0_0/design_IP_RFID_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_processing_system7_0_0 || ORIG_REF_NAME==design_IP_RFID_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_time_pulse_0_0/design_IP_RFID_time_pulse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_time_pulse_0_0 || ORIG_REF_NAME==design_IP_RFID_time_pulse_0_0} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_ps7_0_axi_periph_0/design_IP_RFID_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_IP_RFID_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_rst_ps7_0_50M_0/design_IP_RFID_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_IP_RFID_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/design_IP_RFID_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_ila_0_1 || ORIG_REF_NAME==design_IP_RFID_ila_0_1} -quiet] -quiet

# IP: bd/design_IP_RFID/ip/design_IP_RFID_auto_pc_0/design_IP_RFID_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_IP_RFID_auto_pc_0 || ORIG_REF_NAME==design_IP_RFID_auto_pc_0} -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/design_IP_RFID_ooc.xdc
