# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projets/2020_2/project_RFID/project_RFID.srcs/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/design_RFID_ila_0_0.xci
# IP: The module: 'design_RFID_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_RFID_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_RFID_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/design_RFID_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_RFID_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/projets/2020_2/project_RFID/project_RFID.srcs/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/design_RFID_ila_0_0.xci
# IP: The module: 'design_RFID_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_RFID_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_RFID_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_RFID/ip/design_RFID_ila_0_0/design_RFID_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_RFID_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
