# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projets/2020_2/project_IMU/project_IMU.srcs/sources_1/bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0.xci
# IP: The module: 'design_IP_I2C_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_I2C_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_I2C_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/projets/2020_2/project_IMU/project_IMU.srcs/sources_1/bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0.xci
# IP: The module: 'design_IP_I2C_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_I2C_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IP_I2C/ip/design_IP_I2C_axi_iic_0_0/design_IP_I2C_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_I2C_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
