# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projets/2020_2/project_RFID/project_RFID.srcs/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/design_IP_RFID_ila_0_1.xci
# IP: The module: 'design_IP_RFID_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_RFID_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_RFID_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/design_IP_RFID_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_RFID_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/projets/2020_2/project_RFID/project_RFID.srcs/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/design_IP_RFID_ila_0_1.xci
# IP: The module: 'design_IP_RFID_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_RFID_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_RFID_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_RFID/project_RFID.gen/sources_1/bd/design_IP_RFID/ip/design_IP_RFID_ila_0_1/design_IP_RFID_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IP_RFID_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
