# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Projet_range/zybo-z7-20.xdc

# Block Designs: bd/design_fpga/design_fpga.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga || ORIG_REF_NAME==design_fpga} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_time_pulse_0_0/design_fpga_time_pulse_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_time_pulse_0_0 || ORIG_REF_NAME==design_fpga_time_pulse_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_processing_system7_0_0/design_fpga_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_processing_system7_0_0 || ORIG_REF_NAME==design_fpga_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_xbar_0/design_fpga_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_xbar_0 || ORIG_REF_NAME==design_fpga_xbar_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_ps7_0_axi_periph_0/design_fpga_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_fpga_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_rst_ps7_0_50M_0/design_fpga_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_fpga_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_axi_uartlite_0_0/design_fpga_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_axi_uartlite_0_0 || ORIG_REF_NAME==design_fpga_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_Balise_0_0/design_fpga_Balise_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_Balise_0_0 || ORIG_REF_NAME==design_fpga_Balise_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_Dijkstra_reg_0_0/design_fpga_Dijkstra_reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_Dijkstra_reg_0_0 || ORIG_REF_NAME==design_fpga_Dijkstra_reg_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_IMU_v3_0_0/design_fpga_IMU_v3_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_IMU_v3_0_0 || ORIG_REF_NAME==design_fpga_IMU_v3_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_Timer_ronde_0_0/design_fpga_Timer_ronde_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_Timer_ronde_0_0 || ORIG_REF_NAME==design_fpga_Timer_ronde_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_RFID_reader_0_0/design_fpga_RFID_reader_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_RFID_reader_0_0 || ORIG_REF_NAME==design_fpga_RFID_reader_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_test_interface_0_0/design_fpga_test_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_test_interface_0_0 || ORIG_REF_NAME==design_fpga_test_interface_0_0} -quiet] -quiet

# IP: bd/design_fpga/ip/design_fpga_auto_pc_0/design_fpga_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_fpga_auto_pc_0 || ORIG_REF_NAME==design_fpga_auto_pc_0} -quiet] -quiet

# XDC: d:/Projet_range/project/project.gen/sources_1/bd/design_fpga/design_fpga_ooc.xdc
