# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/zybo-z7-20.xdc

# Block Designs: bd/design_TOP_Dijkstra/design_TOP_Dijkstra.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra || ORIG_REF_NAME==design_TOP_Dijkstra} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_blk_mem_gen_0_0/design_TOP_Dijkstra_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_blk_mem_gen_0_0 || ORIG_REF_NAME==design_TOP_Dijkstra_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_xlconstant_0_0/design_TOP_Dijkstra_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_xlconstant_0_0 || ORIG_REF_NAME==design_TOP_Dijkstra_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_xlconstant_1_0/design_TOP_Dijkstra_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_xlconstant_1_0 || ORIG_REF_NAME==design_TOP_Dijkstra_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_ila_0_0/design_TOP_Dijkstra_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_ila_0_0 || ORIG_REF_NAME==design_TOP_Dijkstra_ila_0_0} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_xlconstant_0_1/design_TOP_Dijkstra_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_xlconstant_0_1 || ORIG_REF_NAME==design_TOP_Dijkstra_xlconstant_0_1} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_clk_wiz_0_0/design_TOP_Dijkstra_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_clk_wiz_0_0 || ORIG_REF_NAME==design_TOP_Dijkstra_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_TOP_Dijkstra/ip/design_TOP_Dijkstra_TOP_dijkstra_0_0/design_TOP_Dijkstra_TOP_dijkstra_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_TOP_Dijkstra_TOP_dijkstra_0_0 || ORIG_REF_NAME==design_TOP_Dijkstra_TOP_dijkstra_0_0} -quiet] -quiet

# XDC: d:/projets/2020_2/project_DIJKSTRA/project_DIJKSTRA.gen/sources_1/bd/design_TOP_Dijkstra/design_TOP_Dijkstra_ooc.xdc
