@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Thu Jun 09 09:20:00 +0200 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 188fec7ef2da41aea7b6047cf526264c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L robot -L xlconstant_v1_1_7 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_dijkstra_behav xil_defaultlib.tb_dijkstra xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 188fec7ef2da41aea7b6047cf526264c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L robot -L xlconstant_v1_1_7 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_dijkstra_behav xil_defaultlib.tb_dijkstra xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
