set_property SRC_FILE_INFO {cfile:D:/projets/2020_2/project_IMU/project_IMU.srcs/constrs_1/imports/Desktop/zybo-z7-20.xdc rfile:../../../project_IMU.srcs/constrs_1/imports/Desktop/zybo-z7-20.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports IMU_I2C_SDA]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports IMU_I2C_SCL]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_IMU_AXI_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_IMU_AXI_i/IP_IMU_0/data_ri2c[0]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[1]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[2]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[3]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[4]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[5]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[6]} {design_IMU_AXI_i/IP_IMU_0/data_ri2c[7]}]]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_IMU_AXI_i/IP_IMU_0/addr_i2c[2]} {design_IMU_AXI_i/IP_IMU_0/addr_i2c[3]} {design_IMU_AXI_i/IP_IMU_0/addr_i2c[5]}]]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_IMU_AXI_i/IP_IMU_0/data_wi2c[0]} {design_IMU_AXI_i/IP_IMU_0/data_wi2c[1]} {design_IMU_AXI_i/IP_IMU_0/data_wi2c[2]} {design_IMU_AXI_i/IP_IMU_0/data_wi2c[3]} {design_IMU_AXI_i/IP_IMU_0/data_wi2c[4]} {design_IMU_AXI_i/IP_IMU_0/data_wi2c[5]} {design_IMU_AXI_i/IP_IMU_0/data_wi2c[6]}]]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[0]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[1]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[2]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[3]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[4]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[5]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[6]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[7]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[8]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[9]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[10]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[11]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[12]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[13]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[14]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/data_wr[15]}]]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/nb_r[0]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/nb_r[1]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/nb_r[2]}]]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/current_state[0]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/current_state[1]} {design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/current_state[2]}]]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list design_IMU_AXI_i/IP_IMU_0/ack_err_i2c]]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_IMU_AXI_i/IP_IMU_0/busy_i2c]]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_IMU_AXI_i/IP_IMU_0/ena_i2c]]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_IMU_AXI_i/IP_IMU_0/flag_data_i2c]]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list design_IMU_AXI_i/IP_IMU_0/U0/IP_IMU_v1_0_S00_AXI_inst/IMU/periph_reg_n_0]]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_IMU_AXI_i/IP_IMU_0/pulse_1ms]]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_IMU_AXI_i/IP_IMU_0/rw_i2c]]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
