# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/projets/2020_2/project_IMU/project_IMU.srcs/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0.xci
# IP: The module: 'design_IMU_AXI_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IMU_AXI_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IMU_AXI_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IMU_AXI_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/projets/2020_2/project_IMU/project_IMU.srcs/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0.xci
# IP: The module: 'design_IMU_AXI_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IMU_AXI_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IMU_AXI_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/projets/2020_2/project_IMU/project_IMU.gen/sources_1/bd/design_IMU_AXI/ip/design_IMU_AXI_rst_ps7_0_50M_0/design_IMU_AXI_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_IMU_AXI_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
